#import "../setup.typ": *
#import "../setup-math.typ": hl, hlx, hlb

= Use of Generative AI

#hl[
In line with good scientific practice, this appendix makes explicit how
generative AI tools were used in the preparation of this thesis.

Generative AI assistants were used as a productivity aid for:
- *Software development:* drafting, refactoring, and debugging parts of the
  accompanying code (`maxwellgp`, `cavity-epgp`, `cavity-bem`, and
  `cavity-benchmark`), and assisting with the plotting and benchmark harness.
- *Writing:* drafting, restructuring, and copy-editing the prose of this
  document, and assisting with Typst typesetting.

All numerical results, figures, and data reported here were produced by the
solvers and scripts described in the appendices, not generated by an AI. Every
AI-assisted output — code, prose, and derivations — was reviewed, checked, and
where necessary corrected by the author, who takes full responsibility for the
content of this thesis. No AI tool was used as a source of factual or physical
claims without independent verification against the cited literature or the
computed results.
]
